name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - "client/android/**"
      - ".github/workflows/android-ci.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "client/android/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        working-directory: client/android/imageProcessor
        run: chmod +x ./gradlew

      - name: Run unit tests
        working-directory: client/android/imageProcessor
        run: ./gradlew testDebugUnitTest
      - name: Run domain module unit tests
        working-directory: client/android/imageProcessor
        run: ./gradlew :domain:test
      - name: Run io module unit tests
        working-directory: client/android/imageProcessor
        run: ./gradlew :io:test
      - name: Run ml module unit tests
        working-directory: client/android/imageProcessor
        run: ./gradlew :ml:test

      - name: Build APK
        working-directory: client/android/imageProcessor
        run: ./gradlew assembleDebug